import { ArrowUpRight } from "lucide-react";
import { Link } from "wouter";

function Mark() { return <span className="grid size-9 grid-cols-2 gap-[2px]" aria-hidden>{[0, 1, 2, 3].map(i => <i key={i} className={`block bg-[#1b1b19] ${i === 1 ? "translate-x-1" : ""}`} />)}</span>; }

function Wordmark() {
  return <div className="flex min-w-0 flex-col leading-none"><span className="font-display text-[1.65rem] tracking-[-.08em] sm:text-[1.9rem]">HANKA</span><span className="hidden pt-1 font-mono text-[8px] uppercase tracking-[.14em] text-[#4d4a43] sm:block">Vouch &amp; Slash Market</span></div>;
}

export default function Home() {
  return <main className="flex min-h-screen flex-col bg-[#ebe9e0] text-[#1b1b19]"><header className="border-b border-[#1b1b19]/25"><div className="market-shell flex h-16 items-center justify-between sm:h-20"><div className="flex items-center gap-3"><Mark /><Wordmark /></div><Link href="/market" className="inline-flex items-center gap-2 text-sm underline underline-offset-4">Enter market <ArrowUpRight className="size-3" /></Link></div></header><section className="market-shell grid flex-1 content-center gap-8 py-8 sm:gap-10 sm:py-10 lg:grid-cols-[1.1fr_.9fr] lg:py-12"><div><p className="eyebrow">HANKA · Social proof market</p><h1 className="mt-4 max-w-4xl font-display text-[clamp(3.7rem,11vw,7.5rem)] leading-[.8] tracking-[-.09em]">Marketplaces for social proof.</h1><p className="mt-5 max-w-xl text-base leading-7 text-[#4d4a43]">A market for vouches, slashes, and compatible social-proof instruments—settled with a wallet and USDC on Solana.</p><Link href="/market" className="mt-7 inline-flex items-center gap-2 bg-[#d54f28] px-5 py-3 text-sm font-medium text-white transition-transform duration-150 hover:bg-[#b93e1c] active:scale-[.97]">Enter market <ArrowUpRight className="size-4" /></Link></div><aside className="relative min-h-64 overflow-hidden border border-[#1b1b19]/30 bg-[#d9d6cc] p-6 sm:min-h-80 sm:p-9"><div className="absolute inset-0 paper-grid opacity-40 mix-blend-multiply" /><div className="relative"><p className="eyebrow">Simple terms</p><div className="mt-8 space-y-4 border-t border-[#1b1b19]/25 pt-5 text-sm leading-6 text-[#4f4a42] sm:mt-12 sm:space-y-5"><p><strong>Buyer-controlled.</strong> Place a request or purchase an active seller listing directly in USDC.</p><p><strong>Exact quantities.</strong> Listings state the exact number of vouches or slashes the selling account makes available.</p><p><strong>Participant-priced.</strong> Market guidance is a live signal, never a platform-set price.</p></div></div></aside></section><footer className="border-t border-[#1b1b19]/25"><div className="market-shell flex flex-wrap items-center justify-between gap-4 py-5 text-xs text-[#4d4a43]"><span>HANKA Vouch &amp; Slash Market · USDC on Solana</span><nav className="flex items-center gap-4"><Link href="/market#terms" className="underline underline-offset-4">Terms</Link><Link href="/ops" className="underline underline-offset-4">Operations</Link></nav></div></footer></main>;
}
