import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { accountPairLabel } from "@/lib/reconciliation";
import { trpc } from "@/lib/trpc";
import { connectWallet, sendUsdcPayment, signWalletMessage } from "@/lib/solanaWallet";
import { BadgeCheck, Check, ExternalLink, Loader2, Plus, WalletCards } from "lucide-react";
import React, { FormEvent, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const money = (value: string | number | null | undefined) => `${Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 6 })} USDC`;
const shortWallet = (wallet: string) => `${wallet.slice(0, 4)}…${wallet.slice(-4)}`;
const instrumentLabel = (instrument?: string) => instrument === "slash" ? "Slashes" : "Vouches";
const legacyBandLabel = (band?: string | null) => band ? `Legacy band: ${band.replaceAll("_", " ")}` : "Exact account quantity";
const pointsPerUnitLabel = (value?: number | null) => value ? `${Number(value).toLocaleString()} points per unit` : "Point value pending (legacy record)";
const USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";

export default function Operations() {
  const [wallet, setWallet] = useState("");
  const [projectName, setProjectName] = useState("");
  const [projectSlug, setProjectSlug] = useState("");
  const [projectDescription, setProjectDescription] = useState("");
  const challenge = trpc.market.walletChallenge.useMutation();
  const operations = trpc.admin.operations.useMutation();
  const payout = trpc.admin.recordPayout.useMutation({ onSuccess: () => void loadOperations() });
  const verifyMetrics = trpc.admin.verifySellerMetrics.useMutation({ onSuccess: () => { toast.success("Seller metrics marked verified."); void loadOperations(); } });
  const createProject = trpc.admin.createProject.useMutation({ onSuccess: () => { toast.success("Compatible project saved."); setProjectName(""); setProjectSlug(""); setProjectDescription(""); void loadOperations(); } });
  const archive = trpc.admin.archiveEligible.useMutation({ onSuccess: result => { toast.success(`${result.archivedRequests + result.archivedSellerCommitments} eligible records compacted.`); void loadOperations(); } });
  const repairLegacyOffer = trpc.admin.setLegacyOfferPoints.useMutation({ onSuccess: result => { toast.success(`${result.publicId} is now eligible for the live board.`); void loadOperations(); } });

  async function proof() {
    if (!wallet) throw new Error("Connect the configured administrator wallet first");
    const issued = await challenge.mutateAsync({ wallet, action: "admin_access" });
    return { challengeId: issued.id, signature: await signWalletMessage(issued.message) };
  }
  async function connectAdminWallet() { try { setWallet(await connectWallet()); toast.success("Wallet connected. Verify access to open the review desk."); } catch (error) { toast.error(error instanceof Error ? error.message : "Wallet connection failed"); } }
  async function loadOperations() { try { const signed = await proof(); await operations.mutateAsync({ wallet, proof: signed }); } catch (error) { toast.error(error instanceof Error ? error.message : "Administrator wallet verification failed"); } }
  async function submitProject(event: FormEvent) { event.preventDefault(); try { const signed = await proof(); await createProject.mutateAsync({ wallet, proof: signed, name: projectName, slug: projectSlug, description: projectDescription || undefined }); } catch (error) { toast.error(error instanceof Error ? error.message : "Project could not be saved"); } }
  async function verifySellerMetricsFor(publicId: string) { try { const signed = await proof(); await verifyMetrics.mutateAsync({ commitmentPublicId: publicId, wallet, proof: signed }); } catch (error) { toast.error(error instanceof Error ? error.message : "Seller metrics could not be verified"); } }
  async function decidePayout(publicId: string, status: "sent" | "withheld", externalReference?: string) { try { const signed = await proof(); await payout.mutateAsync({ commitmentPublicId: publicId, status, wallet, proof: signed, externalReference: status === "sent" ? (externalReference || "Manual USDC payout") : undefined, adminNote: status === "withheld" ? "Held for follow-up" : undefined }); return true; } catch (error) { toast.error(error instanceof Error ? error.message : "Payout record could not be saved"); return false; } }
  async function transferPayout(item: any) { if (!window.confirm(`Send ${money(item.sellerNetUsdc)} to ${item.sellerWallet}? The recipient is loaded from the verified seller record.`)) return; try { const signature = await sendUsdcPayment({ recipientWallet: item.sellerWallet, usdcMint: USDC_MINT, amountUsdc: item.sellerNetUsdc }); const recorded = await decidePayout(item.publicId, "sent", signature); if (recorded) toast.success(`Transfer recorded for ${shortWallet(item.sellerWallet)}.`); else toast.error(`Transfer sent (${signature}) but the payout record needs operator follow-up.`); } catch (error) { toast.error(error instanceof Error ? error.message : "USDC transfer could not be completed"); } }
  async function archiveEligible() { try { const signed = await proof(); await archive.mutateAsync({ wallet, proof: signed }); } catch (error) { toast.error(error instanceof Error ? error.message : "Eligible records could not be compacted"); } }
  async function recordLegacyOfferPoints(offerPublicId: string, pointsPerUnit: number) { try { const signed = await proof(); await repairLegacyOffer.mutateAsync({ offerPublicId, pointsPerUnit, wallet, proof: signed }); } catch (error) { toast.error(error instanceof Error ? error.message : "Point value could not be recorded"); } }

  const data = operations.data;
  return <div className="min-h-screen bg-[#f8f6ef] text-[#1b1b19]"><header className="border-b border-[#1c1c1a]/15"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4"><Link href="/market" className="flex flex-col leading-none"><span className="font-display text-2xl tracking-[-.05em]">HANKA</span><span className="pt-1 font-mono text-[8px] uppercase tracking-[.14em] text-muted-foreground">Vouch &amp; Slash Market</span></Link><Link href="/market" className="inline-flex items-center gap-2 text-sm underline underline-offset-4">Public market <ExternalLink size={14} /></Link></div></header><main data-admin-access="solana-wallet-only" className="operations-shell mx-auto max-w-6xl space-y-8 px-5 py-8"><div className="flex flex-wrap items-start justify-between gap-5 border-b border-[#1c1c1a]/15 pb-7"><div><p className="eyebrow">Private operations</p><h1 className="mt-2 font-display text-4xl tracking-[-.05em]">Review desk.</h1></div><p className="max-w-md text-sm leading-6 text-muted-foreground">Wallet-only access. Connect an authorized Solana wallet and sign a one-time message; no Google or account login is used.</p></div>
    {!wallet ? <WalletNotice onConnect={connectAdminWallet} /> : !data ? <VerificationNotice wallet={wallet} pending={operations.isPending} onVerify={loadOperations} /> : <OperationsDesk data={data} archivePending={archive.isPending} onArchive={archiveEligible} payoutPending={payout.isPending} onPayout={decidePayout} onTransfer={transferPayout} verifyMetricsPending={verifyMetrics.isPending} onVerifyMetrics={verifySellerMetricsFor} repairPending={repairLegacyOffer.isPending} onRepairLegacyOffer={recordLegacyOfferPoints} project={{ name: projectName, slug: projectSlug, description: projectDescription, setName: setProjectName, setSlug: setProjectSlug, setDescription: setProjectDescription, pending: createProject.isPending, submit: submitProject }} />}</main></div>;
}

function OperationsDesk({ data, archivePending, onArchive, payoutPending, onPayout, onTransfer, verifyMetricsPending, onVerifyMetrics, repairPending, onRepairLegacyOffer, project }: any) {
  const reviewQueue = data.commitments.filter((item: any) => item.status === "under_review");
  const evidence = [...data.requests, ...data.commitments.filter((item: any) => item.paymentSignature)];
  const metrics = data.metrics ?? { openSourceOffers: 0, availableUnits: 0, activeAllocations: 0, completedAllocations: 0, listingsMissingPoints: 0 };
  return <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Open source offers" value={metrics.openSourceOffers} /><Metric label="Available units" value={metrics.availableUnits} /><Metric label="Active allocations" value={metrics.activeAllocations} /><Metric label="Completed allocations" value={metrics.completedAllocations} /><Metric label="Recorded payouts" value={data.payouts.length} /><Metric label="Needs points" value={metrics.listingsMissingPoints} /></section><p className="text-xs leading-5 text-muted-foreground">Counts exclude cancelled and archived offer history. A source offer is one account listing; an allocation is one source-to-target unit.</p><div className="flex justify-end"><Button variant="outline" onClick={() => void onArchive()} disabled={archivePending}>{archivePending ? <><Loader2 className="mr-2 size-4 animate-spin" />Compacting…</> : "Compact eligible records"}</Button></div>
    <TransferQueue transfers={data.transferQueue ?? []} pending={payoutPending} onTransfer={onTransfer} />
    <section className="grid gap-7 lg:grid-cols-[1.3fr_.7fr]"><div className="border border-[#1c1c1a]/20 bg-white"><div className="flex items-center justify-between border-b border-[#1c1c1a]/15 px-5 py-4"><h2 className="font-display text-2xl">Completion queue</h2><span className="text-xs uppercase tracking-[.14em] text-muted-foreground">manual review</span></div><div className="divide-y divide-[#1c1c1a]/10">{reviewQueue.length ? reviewQueue.map((item: any) => <div key={item.publicId} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{item.publicId} · @{item.profileHandle}</p><Badge variant="outline">{instrumentLabel(item.instrument)}</Badge></div><p className="mt-1 text-sm font-medium text-[#1b1b19]">{accountPairLabel(item)}</p><p className="mt-1 text-sm text-muted-foreground">Exact quantity {item.quantity.toLocaleString()} · {pointsPerUnitLabel(item.pointsPerUnit)} · {legacyBandLabel(item.vouchBand)}</p><p className="mt-1 text-sm text-muted-foreground">Gross {money(item.grossUsdc ?? Number(item.pricePerVouch) * item.quantity)} · Fee {money(item.platformFeeUsdc)} · Seller net {money(item.sellerNetUsdc)}</p><p className="mt-1 text-xs text-muted-foreground">Seller marked: {item.sellerMarkedDoneAt ? "yes" : "no"} · Buyer confirmed: {item.buyerMarkedDoneAt ? "yes" : item.requestId ? "via linked request" : "no"}</p></div><div className="flex flex-wrap gap-2">{[item.followerCount, item.ethosScore, item.kaitoScore, item.kaitoAura].some(value => value != null) ? <Button variant="outline" size="sm" onClick={() => void onVerifyMetrics(item.publicId)} disabled={verifyMetricsPending || Boolean(item.metricsVerifiedAt)}>{item.metricsVerifiedAt ? <><BadgeCheck size={14} className="mr-1.5" />Verified metrics</> : <><BadgeCheck size={14} className="mr-1.5" />Verify metrics</>}</Button> : null}<Button size="sm" onClick={() => void onPayout(item.publicId, "sent")} disabled={payoutPending}><Check size={14} className="mr-1.5" />Record sent</Button><Button variant="outline" size="sm" onClick={() => void onPayout(item.publicId, "withheld")} disabled={payoutPending}>Hold</Button></div></div>) : <p className="px-5 py-8 text-sm text-muted-foreground">No fully confirmed completions are waiting for review.</p>}</div></div><div className="space-y-7"><SupportInbox messages={data.supportMessages ?? []} /><AuditTrail logs={data.logs} /></div></section>
    <section className="grid gap-7 lg:grid-cols-[.9fr_1.1fr]"><ProjectForm project={project} /><EvidenceTable records={evidence} /></section><LegacyPointRepair offers={data.commitments.filter((item: any) => !item.requestId && !item.parentOfferId && item.status === "open" && !item.pointsPerUnit)} pending={repairPending} onSubmit={onRepairLegacyOffer} /></>;
}

export function TransferQueue({ transfers, pending, onTransfer }: { transfers: any[]; pending: boolean; onTransfer: (item: any) => Promise<void> }) {
  return <section className="border-2 border-[#1c1c1a] bg-[#e8f2e8]"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-[#1c1c1a]/20 px-5 py-4"><div><p className="eyebrow">Transfers</p><h2 className="mt-1 font-display text-3xl">Payout-ready funds.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Only buyer-confirmed and seller-completed allocations appear here. The recipient wallet is loaded from the original seller record, and the transfer amount is the stored seller net after the 5% platform fee.</p></div><span className="border border-[#1c1c1a]/20 bg-white px-3 py-2 font-mono text-xs">{transfers.length} ready</span></div><div className="divide-y divide-[#1c1c1a]/15">{transfers.length ? transfers.map(item => <article key={item.publicId} className="grid gap-5 px-5 py-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.publicId} · @{item.sourceHandle ?? item.profileHandle}</p><span className="bg-[#1c1c1a] px-2 py-1 text-[10px] uppercase tracking-[.12em] text-white">Ready</span></div><p className="mt-2 font-mono text-xs text-muted-foreground">Recipient loaded: {shortWallet(item.sellerWallet)}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p className="text-muted-foreground">Gross</p><p className="mt-1 font-semibold">{money(item.grossUsdc)}</p></div><div><p className="text-muted-foreground">5% fee</p><p className="mt-1 font-semibold">{money(item.platformFeeUsdc)}</p></div><div><p className="text-muted-foreground">Send exactly</p><p className="mt-1 font-semibold text-[#14532d]">{money(item.sellerNetUsdc)}</p></div></div><p className="mt-3 text-xs text-muted-foreground">Buyer confirmed {new Date(item.buyerConfirmedAt).toLocaleString()} · Seller completed {new Date(item.sellerMarkedDoneAt).toLocaleString()}</p></div><Button onClick={() => void onTransfer(item)} disabled={pending} className="bg-[#1b1b19] text-[#f4f0e6]">{pending ? <><Loader2 className="mr-2 size-4 animate-spin" />Sending…</> : <><WalletCards className="mr-2 size-4" />Send exact net</>}</Button></article>) : <div className="px-5 py-8 text-sm text-muted-foreground">No buyer-confirmed seller funds are ready for transfer. Completed items disappear after a payout decision is recorded.</div>}</div></section>;
}
function WalletNotice({ onConnect }: { onConnect: () => Promise<void> }) { return <div className="border border-[#1c1c1a] bg-[#f1eee5] p-7"><p className="eyebrow">Wallet-only access</p><h2 className="mt-2 font-display text-3xl">Connect an authorized administrator wallet.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">This desk has no Google or account login. Connect an allowlisted Solana wallet and sign the one-time verification message to view payment evidence, confirmations, and payout records.</p><Button className="mt-6 bg-[#1b1b19] text-[#f4f0e6]" onClick={() => void onConnect()}><WalletCards className="mr-2 size-4" />Connect administrator wallet</Button></div>; }
function VerificationNotice({ wallet, pending, onVerify }: { wallet: string; pending: boolean; onVerify: () => Promise<void> }) { return <div className="border border-[#1c1c1a]/20 bg-white p-7"><h2 className="font-display text-3xl">Verify review access.</h2><p className="mt-2 text-sm text-muted-foreground">Connected: {shortWallet(wallet)}. Sign a verification message to open the review desk.</p><Button className="mt-5 bg-[#1b1b19] text-[#f4f0e6]" onClick={() => void onVerify()} disabled={pending}>{pending ? <><Loader2 className="mr-2 size-4 animate-spin" />Verifying…</> : "Sign & open review desk"}</Button></div>; }
function AuditTrail({ logs }: { logs: any[] }) { return <div className="border border-[#1c1c1a]/20 bg-[#1b1b19] p-5 text-[#f4f0e6]"><p className="eyebrow text-[#c9c2b2]">Audit trail</p><div className="mt-5 space-y-4">{logs.slice(0, 8).map(log => <div key={log.id} className="border-b border-white/15 pb-3 last:border-0"><p className="text-sm font-medium">{log.eventType.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[#c9c2b2]">{log.entityPublicId} · {new Date(log.createdAt).toLocaleString()}</p></div>)}</div></div>; }
export function SupportInbox({ messages }: { messages: any[] }) { return <section className="border border-[#1c1c1a]/20 bg-white"><div className="flex items-center justify-between border-b border-[#1c1c1a]/15 px-5 py-4"><div><p className="eyebrow">Customer support</p><h2 className="mt-1 font-display text-2xl">Wallet messages</h2></div><span className="text-xs uppercase tracking-[.14em] text-muted-foreground">private</span></div><div className="divide-y divide-[#1c1c1a]/10">{messages.length ? messages.map(message => <article key={message.publicId} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{message.subject}</p><p className="font-mono text-xs text-muted-foreground">{message.publicId}</p></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#37352e]">{message.message}</p><p className="mt-3 text-xs text-muted-foreground">{shortWallet(message.wallet)} · {new Date(message.createdAt).toLocaleString()}</p></article>) : <p className="px-5 py-8 text-sm text-muted-foreground">No customer messages yet.</p>}</div></section>; }
function ProjectForm({ project }: any) { return <form className="border border-[#1c1c1a]/20 bg-white p-5" onSubmit={project.submit}><p className="eyebrow">Compatible projects</p><h2 className="mt-2 font-display text-2xl">Add a project.</h2><div className="mt-5 grid gap-3"><Input value={project.name} onChange={event => project.setName(event.target.value)} placeholder="Project name" required /><Input value={project.slug} onChange={event => project.setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-"))} placeholder="project-slug" required /><Input value={project.description} onChange={event => project.setDescription(event.target.value)} placeholder="Short description (optional)" /><Button type="submit" className="mt-1 bg-[#1b1b19] text-[#f4f0e6]" disabled={project.pending}><Plus className="mr-2 size-4" />Save project</Button></div></form>; }
function LegacyPointRepair({ offers, pending, onSubmit }: { offers: any[]; pending: boolean; onSubmit: (publicId: string, pointsPerUnit: number) => Promise<void> }) { const [values, setValues] = useState<Record<string, string>>({}); if (!offers.length) return null; return <section className="border border-[#1c1c1a]/20 bg-[#f1eee5] p-5"><p className="eyebrow">Legacy listing repair</p><h2 className="mt-2 font-display text-2xl">Record the actual points per unit.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">These open source offers predate the required point value. Enter only the seller’s real per-unit value; saving it makes the offer eligible for the live board. This cannot revise an offer that already has points.</p><div className="mt-5 divide-y divide-[#1c1c1a]/15 border-y border-[#1c1c1a]/15">{offers.map(offer => <form key={offer.publicId} className="flex flex-wrap items-end justify-between gap-4 py-4" onSubmit={event => { event.preventDefault(); const pointsPerUnit = Number(values[offer.publicId]); if (!Number.isInteger(pointsPerUnit) || pointsPerUnit <= 0) { toast.error("Enter a positive whole-number point value."); return; } void onSubmit(offer.publicId, pointsPerUnit); }}><div><p className="font-medium">@{offer.sourceHandle ?? offer.profileHandle} · {offer.publicId}</p><p className="mt-1 text-sm text-muted-foreground">{instrumentLabel(offer.instrument)} · {offer.quantity.toLocaleString()} available unit{offer.quantity === 1 ? "" : "s"} · {money(offer.pricePerVouch)} each</p></div><div className="flex w-full gap-2 sm:w-auto"><Input className="sm:w-52" inputMode="numeric" value={values[offer.publicId] ?? ""} onChange={event => setValues(current => ({ ...current, [offer.publicId]: event.target.value.replace(/\D/g, "") }))} placeholder="Actual points / unit" required /><Button type="submit" className="bg-[#1b1b19] text-[#f4f0e6]" disabled={pending}>Record points</Button></div></form>)}</div></section>; }
export function EvidenceTable({ records }: { records: any[] }) { return <section className="border border-[#1c1c1a]/20 bg-white"><div className="border-b border-[#1c1c1a]/15 px-5 py-4"><h2 className="font-display text-2xl">Payment evidence</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f1eee5] text-xs uppercase tracking-[.12em] text-muted-foreground"><tr><th className="px-5 py-3">Record</th><th className="px-5 py-3">Accounts</th><th className="px-5 py-3">Market</th><th className="px-5 py-3">Exact units</th><th className="px-5 py-3">Points / unit</th><th className="px-5 py-3">State</th><th className="px-5 py-3">Gross</th><th className="px-5 py-3">Signature</th></tr></thead><tbody>{records.map(record => <tr key={record.publicId} className="border-t border-[#1c1c1a]/10"><td className="px-5 py-4 font-medium">{record.publicId}</td><td className="px-5 py-4 text-xs font-medium text-[#1b1b19] whitespace-nowrap">{accountPairLabel(record)}</td><td className="px-5 py-4"><Badge variant="outline">{instrumentLabel(record.instrument)}</Badge><p className="mt-1 text-xs text-muted-foreground">{legacyBandLabel(record.vouchBand)}</p></td><td className="px-5 py-4">{(record.quantity ?? record.requestedQuantity).toLocaleString()}</td><td className="px-5 py-4 text-xs font-medium">{pointsPerUnitLabel(record.pointsPerUnit)}</td><td className="px-5 py-4"><Badge variant="outline">{record.status.replaceAll("_", " ")}</Badge></td><td className="px-5 py-4">{money(record.grossUsdc ?? record.totalUsdc)}</td><td className="max-w-[180px] truncate px-5 py-4 font-mono text-xs">{record.paymentSignature ?? "—"}</td></tr>)}</tbody></table></div></section>; }
function Metric({ label, value, text }: { label: string; value: number | string; text?: boolean }) { return <div className="border border-[#1c1c1a]/20 bg-white p-5"><p className="eyebrow">{label}</p><p className={`mt-2 font-display tracking-[-.05em] ${text ? "text-2xl" : "text-4xl"}`}>{value}</p></div>; }
