import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { accountPairLabel } from "@/lib/reconciliation";
import { trpc } from "@/lib/trpc";
import { connectWallet, signWalletMessage } from "@/lib/solanaWallet";
import { Check, ExternalLink, Loader2, Plus, WalletCards } from "lucide-react";
import React, { FormEvent, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const money = (value: string | number | null | undefined) => `${Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 6 })} USDC`;
const shortWallet = (wallet: string) => `${wallet.slice(0, 4)}…${wallet.slice(-4)}`;
const instrumentLabel = (instrument?: string) => instrument === "slash" ? "Slashes" : "Vouches";
const legacyBandLabel = (band?: string | null) => band ? `Legacy band: ${band.replaceAll("_", " ")}` : "Exact account quantity";

export default function Operations() {
  const [wallet, setWallet] = useState("");
  const [projectName, setProjectName] = useState("");
  const [projectSlug, setProjectSlug] = useState("");
  const [projectDescription, setProjectDescription] = useState("");
  const challenge = trpc.market.walletChallenge.useMutation();
  const operations = trpc.admin.operations.useMutation();
  const payout = trpc.admin.recordPayout.useMutation({ onSuccess: () => void loadOperations() });
  const createProject = trpc.admin.createProject.useMutation({ onSuccess: () => { toast.success("Compatible project saved."); setProjectName(""); setProjectSlug(""); setProjectDescription(""); void loadOperations(); } });
  const archive = trpc.admin.archiveEligible.useMutation({ onSuccess: result => { toast.success(`${result.archivedRequests + result.archivedSellerCommitments} eligible records compacted.`); void loadOperations(); } });

  async function proof() {
    if (!wallet) throw new Error("Connect the configured administrator wallet first");
    const issued = await challenge.mutateAsync({ wallet, action: "admin_access" });
    return { challengeId: issued.id, signature: await signWalletMessage(issued.message) };
  }
  async function connectAdminWallet() { try { setWallet(await connectWallet()); toast.success("Wallet connected. Verify access to open the review desk."); } catch (error) { toast.error(error instanceof Error ? error.message : "Wallet connection failed"); } }
  async function loadOperations() { try { const signed = await proof(); await operations.mutateAsync({ wallet, proof: signed }); } catch (error) { toast.error(error instanceof Error ? error.message : "Administrator wallet verification failed"); } }
  async function submitProject(event: FormEvent) { event.preventDefault(); try { const signed = await proof(); await createProject.mutateAsync({ wallet, proof: signed, name: projectName, slug: projectSlug, description: projectDescription || undefined }); } catch (error) { toast.error(error instanceof Error ? error.message : "Project could not be saved"); } }
  async function decidePayout(publicId: string, status: "sent" | "withheld") { try { const signed = await proof(); await payout.mutateAsync({ commitmentPublicId: publicId, status, wallet, proof: signed, externalReference: status === "sent" ? "Manual USDC payout" : undefined, adminNote: status === "withheld" ? "Held for follow-up" : undefined }); } catch (error) { toast.error(error instanceof Error ? error.message : "Payout record could not be saved"); } }
  async function archiveEligible() { try { const signed = await proof(); await archive.mutateAsync({ wallet, proof: signed }); } catch (error) { toast.error(error instanceof Error ? error.message : "Eligible records could not be compacted"); } }

  const data = operations.data;
  return <div className="min-h-screen bg-[#f8f6ef] text-[#1b1b19]"><header className="border-b border-[#1c1c1a]/15"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4"><Link href="/market" className="font-display text-2xl tracking-[-.05em]">Vouch Market</Link><Link href="/market" className="inline-flex items-center gap-2 text-sm underline underline-offset-4">Public market <ExternalLink size={14} /></Link></div></header><main className="mx-auto max-w-6xl space-y-8 px-5 py-8"><div className="flex flex-wrap items-start justify-between gap-5 border-b border-[#1c1c1a]/15 pb-7"><div><p className="eyebrow">Private operations</p><h1 className="mt-2 font-display text-4xl tracking-[-.05em]">Review desk.</h1></div><p className="max-w-md text-sm leading-6 text-muted-foreground">Wallet-only access. Connect an authorized Solana wallet and sign a one-time message; no Google or account login is used.</p></div>
    {!wallet ? <WalletNotice onConnect={connectAdminWallet} /> : !data ? <VerificationNotice wallet={wallet} pending={operations.isPending} onVerify={loadOperations} /> : <OperationsDesk data={data} archivePending={archive.isPending} onArchive={archiveEligible} payoutPending={payout.isPending} onPayout={decidePayout} project={{ name: projectName, slug: projectSlug, description: projectDescription, setName: setProjectName, setSlug: setProjectSlug, setDescription: setProjectDescription, pending: createProject.isPending, submit: submitProject }} />}</main></div>;
}

function OperationsDesk({ data, archivePending, onArchive, payoutPending, onPayout, project }: any) {
  const reviewQueue = data.commitments.filter((item: any) => item.status === "under_review");
  const evidence = [...data.requests, ...data.commitments.filter((item: any) => item.paymentSignature)];
  return <><section className="grid gap-4 sm:grid-cols-4"><Metric label="Buyer requests" value={data.requests.length} /><Metric label="Seller commitments" value={data.commitments.length} /><Metric label="Recorded payouts" value={data.payouts.length} /><Metric label="Fee total" value={money(data.payouts.reduce((sum: number, item: any) => sum + Number(item.platformFeeUsdc ?? 0), 0))} text /></section><div className="flex justify-end"><Button variant="outline" onClick={() => void onArchive()} disabled={archivePending}>{archivePending ? <><Loader2 className="mr-2 size-4 animate-spin" />Compacting…</> : "Compact eligible records"}</Button></div>
    <section className="grid gap-7 lg:grid-cols-[1.3fr_.7fr]"><div className="border border-[#1c1c1a]/20 bg-white"><div className="flex items-center justify-between border-b border-[#1c1c1a]/15 px-5 py-4"><h2 className="font-display text-2xl">Completion queue</h2><span className="text-xs uppercase tracking-[.14em] text-muted-foreground">manual review</span></div><div className="divide-y divide-[#1c1c1a]/10">{reviewQueue.length ? reviewQueue.map((item: any) => <div key={item.publicId} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{item.publicId} · @{item.profileHandle}</p><Badge variant="outline">{instrumentLabel(item.instrument)}</Badge></div><p className="mt-1 text-sm font-medium text-[#1b1b19]">{accountPairLabel(item)}</p><p className="mt-1 text-sm text-muted-foreground">Exact quantity {item.quantity.toLocaleString()} · {legacyBandLabel(item.vouchBand)}</p><p className="mt-1 text-sm text-muted-foreground">Gross {money(item.grossUsdc ?? Number(item.pricePerVouch) * item.quantity)} · Fee {money(item.platformFeeUsdc)} · Seller net {money(item.sellerNetUsdc)}</p><p className="mt-1 text-xs text-muted-foreground">Seller marked: {item.sellerMarkedDoneAt ? "yes" : "no"} · Buyer confirmed: {item.buyerMarkedDoneAt ? "yes" : item.requestId ? "via linked request" : "no"}</p></div><div className="flex gap-2"><Button size="sm" onClick={() => void onPayout(item.publicId, "sent")} disabled={payoutPending}><Check size={14} className="mr-1.5" />Record sent</Button><Button variant="outline" size="sm" onClick={() => void onPayout(item.publicId, "withheld")} disabled={payoutPending}>Hold</Button></div></div>) : <p className="px-5 py-8 text-sm text-muted-foreground">No fully confirmed completions are waiting for review.</p>}</div></div><AuditTrail logs={data.logs} /></section>
    <section className="grid gap-7 lg:grid-cols-[.9fr_1.1fr]"><ProjectForm project={project} /><EvidenceTable records={evidence} /></section></>;
}

function WalletNotice({ onConnect }: { onConnect: () => Promise<void> }) { return <div className="border border-[#1c1c1a] bg-[#f1eee5] p-7"><p className="eyebrow">Wallet-only access</p><h2 className="mt-2 font-display text-3xl">Connect an authorized administrator wallet.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">This desk has no Google or account login. Connect an allowlisted Solana wallet and sign the one-time verification message to view payment evidence, confirmations, and payout records.</p><Button className="mt-6 bg-[#1b1b19] text-[#f4f0e6]" onClick={() => void onConnect()}><WalletCards className="mr-2 size-4" />Connect administrator wallet</Button></div>; }
function VerificationNotice({ wallet, pending, onVerify }: { wallet: string; pending: boolean; onVerify: () => Promise<void> }) { return <div className="border border-[#1c1c1a]/20 bg-white p-7"><h2 className="font-display text-3xl">Verify review access.</h2><p className="mt-2 text-sm text-muted-foreground">Connected: {shortWallet(wallet)}. Sign a verification message to open the review desk.</p><Button className="mt-5 bg-[#1b1b19] text-[#f4f0e6]" onClick={() => void onVerify()} disabled={pending}>{pending ? <><Loader2 className="mr-2 size-4 animate-spin" />Verifying…</> : "Sign & open review desk"}</Button></div>; }
function AuditTrail({ logs }: { logs: any[] }) { return <div className="border border-[#1c1c1a]/20 bg-[#1b1b19] p-5 text-[#f4f0e6]"><p className="eyebrow text-[#c9c2b2]">Audit trail</p><div className="mt-5 space-y-4">{logs.slice(0, 8).map(log => <div key={log.id} className="border-b border-white/15 pb-3 last:border-0"><p className="text-sm font-medium">{log.eventType.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[#c9c2b2]">{log.entityPublicId} · {new Date(log.createdAt).toLocaleString()}</p></div>)}</div></div>; }
function ProjectForm({ project }: any) { return <form className="border border-[#1c1c1a]/20 bg-white p-5" onSubmit={project.submit}><p className="eyebrow">Compatible projects</p><h2 className="mt-2 font-display text-2xl">Add a project.</h2><div className="mt-5 grid gap-3"><Input value={project.name} onChange={event => project.setName(event.target.value)} placeholder="Project name" required /><Input value={project.slug} onChange={event => project.setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-"))} placeholder="project-slug" required /><Input value={project.description} onChange={event => project.setDescription(event.target.value)} placeholder="Short description (optional)" /><Button type="submit" className="mt-1 bg-[#1b1b19] text-[#f4f0e6]" disabled={project.pending}><Plus className="mr-2 size-4" />Save project</Button></div></form>; }
export function EvidenceTable({ records }: { records: any[] }) { return <section className="border border-[#1c1c1a]/20 bg-white"><div className="border-b border-[#1c1c1a]/15 px-5 py-4"><h2 className="font-display text-2xl">Payment evidence</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f1eee5] text-xs uppercase tracking-[.12em] text-muted-foreground"><tr><th className="px-5 py-3">Record</th><th className="px-5 py-3">Accounts</th><th className="px-5 py-3">Market</th><th className="px-5 py-3">Exact units</th><th className="px-5 py-3">State</th><th className="px-5 py-3">Gross</th><th className="px-5 py-3">Signature</th></tr></thead><tbody>{records.map(record => <tr key={record.publicId} className="border-t border-[#1c1c1a]/10"><td className="px-5 py-4 font-medium">{record.publicId}</td><td className="px-5 py-4 text-xs font-medium text-[#1b1b19] whitespace-nowrap">{accountPairLabel(record)}</td><td className="px-5 py-4"><Badge variant="outline">{instrumentLabel(record.instrument)}</Badge><p className="mt-1 text-xs text-muted-foreground">{legacyBandLabel(record.vouchBand)}</p></td><td className="px-5 py-4">{(record.quantity ?? record.requestedQuantity).toLocaleString()}</td><td className="px-5 py-4"><Badge variant="outline">{record.status.replaceAll("_", " ")}</Badge></td><td className="px-5 py-4">{money(record.grossUsdc ?? record.totalUsdc)}</td><td className="max-w-[180px] truncate px-5 py-4 font-mono text-xs">{record.paymentSignature ?? "—"}</td></tr>)}</tbody></table></div></section>; }
function Metric({ label, value, text }: { label: string; value: number | string; text?: boolean }) { return <div className="border border-[#1c1c1a]/20 bg-white p-5"><p className="eyebrow">{label}</p><p className={`mt-2 font-display tracking-[-.05em] ${text ? "text-2xl" : "text-4xl"}`}>{value}</p></div>; }
