import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { connectWallet, sendUsdcPayment, signWalletMessage } from "@/lib/solanaWallet";
import { ArrowLeft, ArrowUpRight, Check, ChevronRight, Loader2, WalletCards, X } from "lucide-react";
import { FormEvent, ReactNode, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

type Instrument = "vouch" | "slash";
type Payment = { kind: "request" | "offer"; publicId: string; totalUsdc: string; recipientWallet: string; usdcMint: string };
type DialogState = "bid" | "ask" | "activity" | { fill: string; remaining: number; instrument: Instrument } | null;
type MarketRow = { publicId: string; side: "bid" | "ask"; instrument: Instrument; handle: string; exactQuantity: number; price: string; createdAt: Date };

const instruments: Array<{ value: Instrument; label: string }> = [
  { value: "vouch", label: "Vouches" },
  { value: "slash", label: "Slashes" },
];
const activityLabels: Record<string, string> = { awaiting_payment: "Awaiting payment", open: "Open", filled: "Filled", awaiting_review: "Pending completion", completed: "Completed", matched: "Matched", done: "Seller marked done", under_review: "Pending confirmation", paid: "Payout recorded", disputed: "Action required", cancelled: "Cancelled" };
const money = (value: string | number | null | undefined) => `${Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 })} USDC`;
const shortWallet = (wallet: string) => `${wallet.slice(0, 4)}…${wallet.slice(-4)}`;
const instrumentLabel = (instrument?: string) => instrument === "slash" ? "slashes" : "vouches";
const singleInstrument = (instrument: Instrument) => instrument === "slash" ? "slash" : "vouch";

export default function MarketHome() {
  const [wallet, setWallet] = useState("");
  const [dialog, setDialog] = useState<DialogState>(null);
  const [payment, setPayment] = useState<Payment | null>(null);
  const [busy, setBusy] = useState(false);
  const [project, setProject] = useState("commonsmade");
  const [instrumentFilter, setInstrumentFilter] = useState<Instrument | "all">("all");
  const board = trpc.market.board.useQuery();
  const activity = trpc.market.activity.useMutation();
  const utils = trpc.useUtils();
  const createRequest = trpc.market.createRequest.useMutation();
  const verifyRequestPayment = trpc.market.verifyPayment.useMutation();
  const createOffer = trpc.market.createSellerOffer.useMutation();
  const fillRequest = trpc.market.fillRequest.useMutation();
  const startOfferPurchase = trpc.market.initiateOfferPurchase.useMutation();
  const verifyOfferPayment = trpc.market.verifyOfferPayment.useMutation();
  const delistOffer = trpc.market.delistSellerOffer.useMutation();
  const buyerDone = trpc.market.markBuyerDone.useMutation();
  const offerBuyerDone = trpc.market.markOfferBuyerDone.useMutation();
  const sellerDone = trpc.market.markSellerDone.useMutation();
  const cancelRequest = trpc.market.cancelRequest.useMutation();
  const challenge = trpc.market.walletChallenge.useMutation();
  const projects = board.data?.projects ?? [];
  const selectedProject = projects.find(item => item.slug === project) ?? projects[0];

  const marketRows = useMemo<MarketRow[]>(() => {
    const requests = (board.data?.requests ?? [])
      .filter(item => item.projectSlug === project)
      .map(item => ({ publicId: item.publicId, side: "bid" as const, instrument: item.instrument as Instrument, handle: item.targetHandle, exactQuantity: item.requestedQuantity - item.filledQuantity, price: item.pricePerVouch, createdAt: item.createdAt }));
    const offers = (board.data?.sellerOffers ?? [])
      .filter(item => item.projectSlug === project)
      .map(item => ({ publicId: item.publicId, side: "ask" as const, instrument: item.instrument as Instrument, handle: item.profileHandle, exactQuantity: item.quantity, price: item.pricePerVouch, createdAt: item.createdAt }));
    return [...requests, ...offers]
      .filter(item => instrumentFilter === "all" || item.instrument === instrumentFilter)
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }, [board.data?.requests, board.data?.sellerOffers, instrumentFilter, project]);

  async function refresh() { await utils.market.board.invalidate(); }
  async function connect() {
    try { setBusy(true); setWallet(await connectWallet()); toast.success("Wallet connected"); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Wallet connection failed"); }
    finally { setBusy(false); }
  }
  async function walletProof(action: "buyer_request" | "seller_offer" | "seller_fill" | "buyer_done" | "seller_done" | "cancel_request" | "seller_delist" | "offer_buy" | "offer_buyer_done" | "activity_view") {
    if (!wallet) throw new Error("Connect your wallet first");
    const item = await challenge.mutateAsync({ wallet, action });
    return { challengeId: item.id, signature: await signWalletMessage(item.message) };
  }
  async function openActivity() {
    try { setBusy(true); const proof = await walletProof("activity_view"); await activity.mutateAsync({ wallet, proof }); setDialog("activity"); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not load wallet activity"); }
    finally { setBusy(false); }
  }
  async function settlePayment() {
    if (!payment) return;
    try {
      setBusy(true);
      if (!payment.recipientWallet || !payment.usdcMint) throw new Error("Payment instructions are unavailable. Please reconnect and try again.");
      const signature = await sendUsdcPayment({ ...payment, amountUsdc: payment.totalUsdc });
      if (payment.kind === "request") await verifyRequestPayment.mutateAsync({ publicId: payment.publicId, wallet, signature });
      else await verifyOfferPayment.mutateAsync({ publicId: payment.publicId, wallet, signature });
      toast.success(payment.kind === "request" ? "Payment verified. Your bid is live." : "Payment verified. The seller has been notified.");
      setPayment(null); setDialog(null); await refresh();
    } catch (error) { toast.error(error instanceof Error ? error.message : "The payment could not be completed"); }
    finally { setBusy(false); }
  }
  async function buyListing(publicId: string) {
    if (!wallet) { void connect(); return; }
    try { setBusy(true); const proof = await walletProof("offer_buy"); const created = await startOfferPurchase.mutateAsync({ publicId, wallet, proof }); setPayment({ kind: "offer", ...created }); setDialog("bid"); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not reserve this seller listing"); }
    finally { setBusy(false); }
  }
  async function markDone(kind: "request-buyer" | "offer-buyer" | "seller", publicId: string) {
    try {
      setBusy(true);
      if (kind === "request-buyer") { const proof = await walletProof("buyer_done"); await buyerDone.mutateAsync({ publicId, wallet, proof }); }
      else if (kind === "offer-buyer") { const proof = await walletProof("offer_buyer_done"); await offerBuyerDone.mutateAsync({ publicId, wallet, proof }); }
      else { const proof = await walletProof("seller_done"); await sellerDone.mutateAsync({ publicId, wallet, proof }); }
      toast.success("Completion recorded."); await refresh();
    } catch (error) { toast.error(error instanceof Error ? error.message : "Could not mark completion"); }
    finally { setBusy(false); }
  }
  async function delist(publicId: string) { try { setBusy(true); const proof = await walletProof("seller_delist"); await delistOffer.mutateAsync({ publicId, wallet, proof }); toast.success("Listing removed."); await refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not remove this listing"); } finally { setBusy(false); } }
  async function cancel(publicId: string) { try { setBusy(true); const proof = await walletProof("cancel_request"); await cancelRequest.mutateAsync({ publicId, wallet, proof }); toast.success("Unpaid bid cancelled."); await refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not cancel this bid"); } finally { setBusy(false); } }

  return <div className="min-h-screen bg-[#101612] text-[#f2efe4] selection:bg-[#8fd3a1] selection:text-[#101612]">
    <header className="border-b border-[#e9e5d5]/15 bg-[#101612]/90 backdrop-blur"><div className="market-shell flex h-16 items-center justify-between gap-3 sm:h-20"><Link href="/" className="flex items-center gap-2 sm:gap-3"><Mark /><span className="font-display text-[1.45rem] leading-none tracking-[-0.07em] sm:text-[1.8rem]">Vouch Market</span></Link><nav className="hidden items-center gap-6 text-sm text-[#c9c7bb] md:flex"><a href="#market" className="transition-colors hover:text-white">Markets</a><a href="#terms" className="transition-colors hover:text-white">Terms</a></nav>{wallet ? <Button variant="outline" className="border-[#e9e5d5]/30 bg-transparent font-mono text-xs text-[#f2efe4] hover:bg-white/10 hover:text-white" onClick={() => void openActivity()}>{shortWallet(wallet)}</Button> : <Button onClick={() => void connect()} disabled={busy} className="bg-[#f2efe4] text-[#101612] hover:bg-white"><WalletCards className="mr-2 size-4" />Connect wallet</Button>}</div></header>
    <main>
      <section className="border-b border-[#e9e5d5]/15 bg-[radial-gradient(circle_at_50%_-40%,#25412f_0%,#101612_55%)]"><div className="market-shell py-7 sm:py-9"><Link href="/" className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[.15em] text-[#a4a89b] transition-colors hover:text-white"><ArrowLeft className="size-3" />Vouch Market</Link><div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1fr)_auto]"><div><p className="eyebrow text-[#9ee0ae]">Commons market</p><h1 className="mt-2 max-w-3xl font-display text-[clamp(3rem,7vw,6.5rem)] leading-[.8] tracking-[-.08em]">Trade the signal.</h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#c4c5b8] sm:text-base">A single market ledger for CommonsMade vouches and slashes. Every row states the exact account quantity being offered or requested.</p></div><div className="flex flex-wrap content-end gap-2 lg:justify-end"><Button size="sm" className="bg-[#92d5a2] text-[#102016] hover:bg-[#b0e5bc]" onClick={() => setDialog("bid")}>Post a bid <ArrowUpRight className="ml-2 size-3" /></Button><Button size="sm" variant="outline" className="border-[#e9e5d5]/35 bg-transparent text-[#f2efe4] hover:bg-white/10 hover:text-white" onClick={() => setDialog("ask")}>List your account</Button></div></div></div></section>
      <section id="market" className="border-b border-[#e9e5d5]/15 bg-[#121a15]"><div className="market-shell py-4"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-center"><div className="flex flex-wrap items-center gap-3"><p className="eyebrow text-[#a4a89b]">Project</p><ProjectSelect value={project} setValue={setProject} projects={projects} dark /><p className="max-w-md text-xs text-[#b8b9ae]">{selectedProject?.description ?? "Compatible Commons projects can be added by the marketplace administrator."}</p></div><div className="flex w-full rounded-full border border-[#e9e5d5]/20 p-1 sm:w-auto">{(["all", "vouch", "slash"] as const).map(value => <button key={value} onClick={() => setInstrumentFilter(value)} className={`min-w-0 flex-1 rounded-full px-3 py-2 text-xs font-medium transition-colors sm:flex-none ${instrumentFilter === value ? "bg-[#f2efe4] text-[#101612]" : "text-[#c6c9bd] hover:bg-white/10 hover:text-white"}`}>{value === "all" ? "All" : value === "vouch" ? "Vouches" : "Slashes"}</button>)}</div></div></div></section>
      <section className="market-shell grid gap-5 py-6 xl:grid-cols-[minmax(0,1fr)_240px]"><div className="overflow-hidden border border-[#e9e5d5]/20 bg-[#0d130f]"><div className="flex items-center justify-between border-b border-[#e9e5d5]/20 px-4 py-3 sm:px-5"><div><p className="eyebrow text-[#9ee0ae]">Live board</p><h2 className="mt-1 font-display text-3xl tracking-[-.06em] sm:text-4xl">Markets</h2></div><span className="font-mono text-xs text-[#a4a89b]">{String(marketRows.length).padStart(2, "0")} live</span></div><div className="hidden grid-cols-[42px_70px_minmax(120px,1.25fr)_100px_112px_112px_70px] gap-3 border-b border-[#e9e5d5]/15 bg-[#152019] px-5 py-2 text-[10px] uppercase tracking-[.13em] text-[#a4a89b] lg:grid"><span>#</span><span>Side</span><span>Account</span><span>Market</span><span>Exact units</span><span>Quote</span><span /></div>{board.isLoading ? <Loading /> : marketRows.length ? marketRows.map((row, index) => <LeaderboardRow key={row.publicId} row={row} rank={index + 1} busy={busy} connected={Boolean(wallet)} onFill={() => setDialog({ fill: row.publicId, remaining: row.exactQuantity, instrument: row.instrument })} onBuy={() => void buyListing(row.publicId)} />) : <Empty instrument={instrumentFilter} onBid={() => setDialog("bid")} onAsk={() => setDialog("ask")} />}</div><aside className="grid content-start gap-3 sm:grid-cols-2 xl:grid-cols-1"><Midpoint label="Vouch midpoint" value={board.data?.suggestedPriceByInstrument?.vouch} instrument="vouch" /><Midpoint label="Slash midpoint" value={board.data?.suggestedPriceByInstrument?.slash} instrument="slash" /><div className="border border-[#e9e5d5]/20 bg-[#17201a] p-4"><p className="eyebrow text-[#a4a89b]">How to read</p><p className="mt-3 text-sm leading-6 text-[#c8cabf]">Green bids are open demand. Charcoal asks are account-specific supply. Each row shows the exact number of vouches or slashes being traded.</p></div></aside></section>
      <section id="terms" className="border-t border-[#e9e5d5]/15 bg-[#090e0b]"><div className="market-shell grid gap-5 py-7 md:grid-cols-[.7fr_1.3fr]"><p className="eyebrow text-[#9ba094]">Market terms</p><p className="max-w-3xl text-sm leading-6 text-[#d6d7cd]">Buyer payments use Circle-issued USDC on Solana. A <strong>5% platform fee</strong> is deducted from the seller’s gross amount. Prices remain participant-set.</p></div></section>
    </main>
    <footer className="market-shell flex flex-wrap items-center justify-between gap-4 py-5 text-xs text-[#989d91]"><span>Vouch Market · CommonsMade first</span><span>USDC on Solana</span></footer>
    <BidDialog open={dialog === "bid" || Boolean(payment?.kind === "offer")} close={() => { setDialog(null); setPayment(null); }} wallet={wallet} connect={connect} projects={projects} project={project} setProject={setProject} create={createRequest} sign={walletProof} payment={payment} setPayment={setPayment} pay={settlePayment} busy={busy} />
    <AskDialog open={dialog === "ask"} close={() => setDialog(null)} wallet={wallet} connect={connect} projects={projects} project={project} setProject={setProject} create={createOffer} sign={walletProof} refresh={refresh} busy={busy} />
    <FillDialog target={typeof dialog === "object" && dialog && "fill" in dialog ? dialog : null} close={() => setDialog(null)} wallet={wallet} connect={connect} fill={fillRequest} sign={walletProof} busy={busy} />
    <ActivityDialog open={dialog === "activity"} close={() => setDialog(null)} wallet={wallet} data={activity.data} busy={busy} markDone={markDone} delist={delist} cancel={cancel} />
  </div>;
}

function Mark() { return <span className="grid size-7 grid-cols-2 gap-[2px] sm:size-8" aria-hidden>{[0, 1, 2, 3].map(index => <i key={index} className={`block bg-[#f2efe4] ${index === 1 ? "translate-x-1" : ""}`} />)}</span>; }
function Loading() { return <div className="h-60 animate-pulse bg-[#101612]" />; }
function Midpoint({ label, value, instrument }: { label: string; value?: string | null; instrument: Instrument }) { return <div className={`border p-4 ${instrument === "vouch" ? "border-[#8fcfa0]/35 bg-[#183223]" : "border-[#c3848a]/35 bg-[#2b1d1f]"}`}><p className="eyebrow text-[#d3d5ca]">{label}</p><p className="mt-3 font-display text-3xl tracking-[-.06em]">{value ? money(value) : "—"}</p><p className="mt-1 text-xs text-[#c6c7be]">Indicative USDC per {singleInstrument(instrument)}</p></div>; }
function Empty({ instrument, onBid, onAsk }: { instrument: Instrument | "all"; onBid: () => void; onAsk: () => void }) { const subject = instrument === "all" ? "market" : instrumentLabel(instrument); return <div className="m-4 border border-dashed border-[#e9e5d5]/25 p-5 text-sm text-[#b9bcb0]"><p>No live {subject} bids or asks for this project.</p><div className="mt-3 flex gap-4"><button onClick={onBid} className="underline underline-offset-4 hover:text-white">Post a bid</button><button onClick={onAsk} className="underline underline-offset-4 hover:text-white">List your account</button></div></div>; }
function LeaderboardRow({ row, rank, busy, connected, onFill, onBuy }: { row: MarketRow; rank: number; busy: boolean; connected: boolean; onFill: () => void; onBuy: () => void }) { const isBid = row.side === "bid"; const action = isBid ? onFill : onBuy; const tone = isBid ? "border-[#75b989]/35 bg-[#183123]/70 hover:bg-[#1d3d2b]" : "border-[#e9e5d5]/15 bg-[#151d18] hover:bg-[#1b251f]"; const rowAction = connected ? <TradeAction bid={isBid} busy={busy} disabled={isBid && !row.exactQuantity} onClick={action} /> : <span className="font-mono text-xs text-[#899085]">—</span>; return <article className={`border-b px-4 py-3 transition-colors sm:px-5 ${tone}`}><div className="lg:hidden"><div className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-3"><span className="font-mono text-xs text-[#aeb2a6]">{String(rank).padStart(2, "0")}</span><div className="min-w-0"><div className="flex items-center gap-2"><span className={`eyebrow ${isBid ? "text-[#a5e5b4]" : "text-[#d8d7cf]"}`}>{isBid ? "Bid" : "Ask"}</span><InstrumentBadge instrument={row.instrument} /></div><h3 className="mt-1 truncate font-display text-2xl tracking-[-.045em]">@{row.handle}</h3></div>{rowAction}</div><div className="mt-3 grid grid-cols-2 border-t border-[#e9e5d5]/15 pt-2"><Datum label={isBid ? "Exact wanted" : "Exact available"} value={row.exactQuantity.toLocaleString()} /><Datum label="Quote" value={money(row.price)} /></div></div><div className="hidden grid-cols-[42px_70px_minmax(120px,1.25fr)_100px_112px_112px_70px] items-center gap-3 lg:grid"><span className="font-mono text-xs text-[#aeb2a6]">{String(rank).padStart(2, "0")}</span><span className={`font-mono text-xs uppercase tracking-[.1em] ${isBid ? "text-[#a5e5b4]" : "text-[#d8d7cf]"}`}>{isBid ? "Bid" : "Ask"}</span><div className="min-w-0"><p className="truncate font-display text-xl tracking-[-.04em]">@{row.handle}</p><p className="mt-0.5 font-mono text-[10px] text-[#9ba094]">{row.publicId}</p></div><InstrumentBadge instrument={row.instrument} /><span className="font-mono text-sm text-[#f2efe4]">{row.exactQuantity.toLocaleString()}</span><span className="font-mono text-sm text-[#f2efe4]">{money(row.price)}</span>{rowAction}</div></article>; }
function InstrumentBadge({ instrument }: { instrument: Instrument }) { return <span className={`w-fit rounded-full border px-2 py-1 text-[10px] uppercase tracking-[.1em] ${instrument === "slash" ? "border-[#cf8a91]/50 bg-[#502d31] text-[#ffc9ce]" : "border-[#9edbad]/45 bg-[#234630] text-[#c8f0d0]"}`}>{instrument}</span>; }
function TradeAction({ bid, busy, disabled, onClick }: { bid: boolean; busy: boolean; disabled: boolean; onClick: () => void }) { return <Button size="sm" variant={bid ? "outline" : "default"} className={bid ? "border-[#a7dfb4]/45 bg-transparent text-[#dff5e4] hover:bg-[#9edfad] hover:text-[#132018]" : "bg-[#f2efe4] text-[#102016] hover:bg-white"} onClick={onClick} disabled={busy || disabled}>{bid ? "Fill" : "Buy"}<ChevronRight className="ml-1 size-3" /></Button>; }
function Datum({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-[.11em] text-[#9da297]">{label}</p><p className="mt-1 truncate text-sm text-[#f2efe4]">{value}</p></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="grid gap-2"><Label className="text-sm font-medium">{label}</Label>{children}</div>; }
function ProjectSelect({ value, setValue, projects, dark = false }: { value: string; setValue: (value: string) => void; projects: any[]; dark?: boolean }) { return <Select value={value} onValueChange={setValue}><SelectTrigger className={dark ? "h-9 w-48 border-[#e9e5d5]/25 bg-transparent text-[#f2efe4]" : ""}><SelectValue /></SelectTrigger><SelectContent>{projects.map(item => <SelectItem key={item.slug} value={item.slug}>{item.name}</SelectItem>)}</SelectContent></Select>; }
function InstrumentSelect({ value, setValue }: { value: Instrument; setValue: (value: Instrument) => void }) { return <Select value={value} onValueChange={setValue as (value: string) => void}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{instruments.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select>; }
function Gate({ connect }: { connect: () => Promise<void> }) { return <div className="mt-5 border border-[#1b1b19]/20 bg-white p-6 text-[#1b1b19]"><p className="font-display text-2xl tracking-[-.04em]">Connect to continue.</p><p className="mt-2 text-sm leading-6 text-[#625d54]">Your wallet authorizes payments and action-specific confirmations. No public account is created.</p><Button onClick={() => void connect()} className="mt-5 bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]"><WalletCards className="mr-2 size-4" />Connect Phantom</Button></div>; }

function BidDialog({ open, close, wallet, connect, projects, project, setProject, create, sign, payment, setPayment, pay, busy }: any) {
  const [handle, setHandle] = useState(""); const [instrument, setInstrument] = useState<Instrument>("vouch"); const [quantity, setQuantity] = useState("1"); const [price, setPrice] = useState("0.50"); const exactTotal = Number(quantity || 0) * Number(price || 0);
  async function submit(event: FormEvent) { event.preventDefault(); try { if (!wallet) throw new Error("Connect your wallet first"); const proof = await sign("buyer_request"); const created = await create.mutateAsync({ wallet, targetHandle: handle, projectSlug: project, instrument, quantity: Number(quantity), pricePerVouch: Number(price), proof }); setPayment({ kind: "request", ...created }); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create bid"); } }
  return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#1b1b19] bg-[#f4f0e6] sm:max-w-lg"><DialogHeader><p className="eyebrow">{payment?.kind === "offer" ? "Direct purchase" : "New market bid"}</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">{payment?.kind === "offer" ? "Buy listed inventory." : "Fund your exact bid."}</DialogTitle></DialogHeader>{!wallet ? <Gate connect={connect} /> : payment ? <div className="mt-4 space-y-5"><div className="border border-[#1b1b19]/25 bg-white p-5"><p className="eyebrow">Exact payment due</p><p className="mt-2 font-display text-4xl tracking-[-.06em]">{money(payment.totalUsdc)}</p><p className="mt-3 text-sm leading-6 text-[#5e594f]">Your wallet will open to approve the exact Circle-issued USDC transfer.</p></div><Button className="w-full bg-[#28573a] text-white hover:bg-[#1d442d]" onClick={() => void pay()} disabled={busy}>{busy ? <><Loader2 className="mr-2 size-4 animate-spin" />Confirming…</> : "Open wallet & pay"}</Button></div> : <form className="mt-4 space-y-5" onSubmit={submit}><Field label="Project"><ProjectSelect value={project} setValue={setProject} projects={projects} /></Field><Field label="Market"><InstrumentSelect value={instrument} setValue={setInstrument} /></Field><Field label="Target X handle"><Input value={handle} onChange={event => setHandle(event.target.value)} placeholder="commonsmade" required /></Field><Field label={`Exact ${instruments.find(item => item.value === instrument)?.label.toLowerCase()} wanted`}><Input type="number" min="1" value={quantity} onChange={event => setQuantity(event.target.value)} required /></Field><Field label={`Bid per ${singleInstrument(instrument)} (USDC)`}><Input type="number" min="0.000001" step="0.000001" value={price} onChange={event => setPrice(event.target.value)} required /></Field><div className="border-y border-[#1b1b19]/20 py-3 text-sm"><div className="flex justify-between"><span>Exact USDC payment</span><strong>{money(exactTotal)}</strong></div><p className="mt-2 text-xs leading-5 text-[#625d54]">This bid is for exactly {Number(quantity || 0).toLocaleString()} {instrumentLabel(instrument)}. A 5% marketplace fee is calculated from seller proceeds, not added to this payment.</p></div><Button type="submit" className="w-full bg-[#28573a] text-white hover:bg-[#1d442d]" disabled={busy}>Continue to USDC payment</Button></form>}</DialogContent></Dialog>;
}
function AskDialog({ open, close, wallet, connect, projects, project, setProject, create, sign, refresh, busy }: any) {
  const [handle, setHandle] = useState(""); const [instrument, setInstrument] = useState<Instrument>("vouch"); const [quantity, setQuantity] = useState("1"); const [price, setPrice] = useState("0.50");
  async function submit(event: FormEvent) { event.preventDefault(); try { if (!wallet) throw new Error("Connect your wallet first"); const proof = await sign("seller_offer"); const result = await create.mutateAsync({ wallet, profileHandle: handle, projectSlug: project, instrument, quantity: Number(quantity), pricePerVouch: Number(price), proof }); toast.success(`${result.publicId} is now live.`); await refresh(); close(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not post listing"); } }
  return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#1b1b19] bg-[#f4f0e6] sm:max-w-lg"><DialogHeader><p className="eyebrow">New market ask</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">List your account.</DialogTitle></DialogHeader>{!wallet ? <Gate connect={connect} /> : <form className="mt-4 space-y-5" onSubmit={submit}><Field label="Project"><ProjectSelect value={project} setValue={setProject} projects={projects} /></Field><Field label="Market"><InstrumentSelect value={instrument} setValue={setInstrument} /></Field><Field label="Your X handle"><Input value={handle} onChange={event => setHandle(event.target.value)} placeholder="yourhandle" required /></Field><Field label={`Exact ${instruments.find(item => item.value === instrument)?.label.toLowerCase()} available on this account`}><Input type="number" min="1" value={quantity} onChange={event => setQuantity(event.target.value)} required /></Field><Field label={`Ask per ${singleInstrument(instrument)} (USDC)`}><Input type="number" min="0.000001" step="0.000001" value={price} onChange={event => setPrice(event.target.value)} required /></Field><p className="text-xs leading-5 text-[#625d54]">Your listing tells buyers the exact number of {instrumentLabel(instrument)} this account can provide. You can remove an open listing at any time.</p><Button type="submit" className="w-full bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]" disabled={busy}>Sign & post listing</Button></form>}</DialogContent></Dialog>;
}
function FillDialog({ target, close, wallet, connect, fill, sign, busy }: any) {
  const [handle, setHandle] = useState(""); const [quantity, setQuantity] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); try { if (!wallet) throw new Error("Connect your wallet first"); const proof = await sign("seller_fill"); const result = await fill.mutateAsync({ requestPublicId: target.fill, wallet, profileHandle: handle, quantity: Number(quantity), proof }); toast.success(`${result.publicId} is matched to the bid.`); close(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not fill bid"); } }
  return <Dialog open={Boolean(target)} onOpenChange={value => !value && close()}><DialogContent className="border-[#1b1b19] bg-[#f4f0e6] sm:max-w-lg"><DialogHeader><p className="eyebrow">Fill market bid</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">Commit your {target ? instrumentLabel(target.instrument) : "position"}.</DialogTitle></DialogHeader>{!wallet ? <Gate connect={connect} /> : <form className="mt-4 space-y-5" onSubmit={submit}><p className="text-sm leading-6 text-[#5e594f]">Exactly {target?.remaining.toLocaleString()} {instrumentLabel(target?.instrument)} remain on {target?.fill}.</p><Field label="Your X handle"><Input value={handle} onChange={event => setHandle(event.target.value)} placeholder="yourhandle" required /></Field><Field label="Exact quantity to fill"><Input type="number" min="1" max={target?.remaining} value={quantity} onChange={event => setQuantity(event.target.value)} required /></Field><Button type="submit" className="w-full bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]" disabled={busy}>Sign & fill bid</Button></form>}</DialogContent></Dialog>;
}
function ActivityDialog({ open, close, wallet, data, busy, markDone, delist, cancel }: any) { return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#1b1b19] bg-[#f4f0e6] sm:max-w-xl"><DialogHeader><p className="eyebrow">Wallet activity</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">{wallet && shortWallet(wallet)}</DialogTitle></DialogHeader><div className="mt-4 space-y-7"><ActivityGroup title="Market bids">{data?.requests?.length ? data.requests.map((item: any) => <ActivityRow key={item.publicId} text={`${item.publicId} · @${item.targetHandle}`} detail={`${item.filledQuantity}/${item.requestedQuantity} ${instrumentLabel(item.instrument)} filled · ${money(item.totalUsdc)} · ${activityLabels[item.status] ?? item.status}`} action={item.status === "filled" && !item.buyerMarkedDoneAt ? <Button size="sm" onClick={() => void markDone("request-buyer", item.publicId)} disabled={busy}>Confirm task</Button> : item.status === "awaiting_payment" ? <Button size="sm" variant="outline" onClick={() => void cancel(item.publicId)} disabled={busy}>Cancel</Button> : null} />) : <Muted text="No market bids for this wallet." />}</ActivityGroup><ActivityGroup title="Direct purchases">{data?.purchases?.length ? data.purchases.map((item: any) => <ActivityRow key={item.publicId} text={`${item.publicId} · @${item.profileHandle}`} detail={`${item.quantity} ${instrumentLabel(item.instrument)} · ${money(item.grossUsdc)} · ${activityLabels[item.status] ?? item.status}`} action={["matched", "done"].includes(item.status) && !item.buyerMarkedDoneAt ? <Button size="sm" onClick={() => void markDone("offer-buyer", item.publicId)} disabled={busy}>Confirm task</Button> : null} />) : <Muted text="No direct purchases for this wallet." />}</ActivityGroup><ActivityGroup title="Your listings & fills">{data?.fills?.length ? data.fills.map((item: any) => <ActivityRow key={item.publicId} text={`${item.publicId} · @${item.profileHandle}`} detail={`${item.quantity} ${instrumentLabel(item.instrument)} · ${money(item.pricePerVouch)} each · ${activityLabels[item.status] ?? item.status}`} action={item.status === "open" ? <Button size="sm" variant="outline" onClick={() => void delist(item.publicId)} disabled={busy}><X className="mr-1 size-3" />Delist</Button> : item.status === "matched" ? <Button size="sm" onClick={() => void markDone("seller", item.publicId)} disabled={busy}><Check className="mr-1 size-3" />Mark done</Button> : null} />) : <Muted text="No seller activity for this wallet." />}</ActivityGroup><p className="border-t border-[#1b1b19]/20 pt-4 text-xs leading-5 text-[#625d54]">Completion marks are participant statements. They do not automatically release payment.</p></div></DialogContent></Dialog>; }
function ActivityGroup({ title, children }: { title: string; children: ReactNode }) { return <div><p className="eyebrow">{title}</p><div className="mt-3 space-y-2">{children}</div></div>; }
function ActivityRow({ text, detail, action }: { text: string; detail: string; action?: ReactNode }) { return <div className="flex flex-wrap items-center justify-between gap-3 border border-[#1b1b19]/20 bg-white p-4"><div><p className="text-sm font-semibold">{text}</p><p className="mt-1 text-xs text-[#686158]">{detail}</p></div>{action}</div>; }
function Muted({ text }: { text: string }) { return <p className="text-sm text-[#686158]">{text}</p>; }
