import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { connectWallet, sendUsdcPayment, signWalletMessage } from "@/lib/solanaWallet";
import { ArrowLeft, ArrowUpRight, Check, Loader2, WalletCards, X } from "lucide-react";
import { FormEvent, ReactNode, useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type Band = "under_1k" | "1k_5k" | "5k_10k" | "10k_25k" | "25k_50k" | "50k_plus";
type Payment = { kind: "request" | "offer"; publicId: string; totalUsdc: string; recipientWallet: string; usdcMint: string };
type Modal = "buy" | "sell" | "activity" | { fill: string; remaining: number; projectSlug: string } | { buyOffer: string } | null;

const bands: { value: Band; label: string }[] = [
  { value: "under_1k", label: "Under 1k" }, { value: "1k_5k", label: "1k–5k" }, { value: "5k_10k", label: "5k–10k" },
  { value: "10k_25k", label: "10k–25k" }, { value: "25k_50k", label: "25k–50k" }, { value: "50k_plus", label: "50k+" },
];
const stateLabel: Record<string, string> = { awaiting_payment: "Awaiting payment", open: "Open", filled: "Filled", awaiting_review: "Under review", completed: "Completed", matched: "Matched", done: "Seller marked done", under_review: "Under review", paid: "Payout recorded", disputed: "Needs review", cancelled: "Cancelled" };
const money = (value: string | number | null | undefined) => `${Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 })} USDC`;
const shortWallet = (wallet: string) => `${wallet.slice(0, 4)}…${wallet.slice(-4)}`;

export default function MarketHome() {
  const [wallet, setWallet] = useState("");
  const [modal, setModal] = useState<Modal>(null);
  const [payment, setPayment] = useState<Payment | null>(null);
  const [busy, setBusy] = useState(false);
  const [project, setProject] = useState("commonsmade");
  const board = trpc.market.board.useQuery();
  const activity = trpc.market.activity.useMutation();
  const utils = trpc.useUtils();
  const createRequest = trpc.market.createRequest.useMutation();
  const verifyRequestPayment = trpc.market.verifyPayment.useMutation();
  const createOffer = trpc.market.createSellerOffer.useMutation();
  const fill = trpc.market.fillRequest.useMutation();
  const startOfferPurchase = trpc.market.initiateOfferPurchase.useMutation();
  const verifyOfferPayment = trpc.market.verifyOfferPayment.useMutation();
  const delist = trpc.market.delistSellerOffer.useMutation();
  const buyerDone = trpc.market.markBuyerDone.useMutation();
  const offerBuyerDone = trpc.market.markOfferBuyerDone.useMutation();
  const sellerDone = trpc.market.markSellerDone.useMutation();
  const cancelRequest = trpc.market.cancelRequest.useMutation();
  const challenge = trpc.market.walletChallenge.useMutation();
  const projects = board.data?.projects ?? [];
  const selectedProject = projects.find(item => item.slug === project) ?? projects[0];
  const requests = (board.data?.requests ?? []).filter(item => item.projectSlug === project);
  const offers = (board.data?.sellerOffers ?? []).filter(item => item.projectSlug === project);

  async function refresh() { await utils.market.board.invalidate(); }
  async function connect() { try { setBusy(true); setWallet(await connectWallet()); toast.success("Wallet connected"); } catch (error) { toast.error(error instanceof Error ? error.message : "Wallet connection failed"); } finally { setBusy(false); } }
  async function walletProof(action: "buyer_request" | "seller_offer" | "seller_fill" | "buyer_done" | "seller_done" | "cancel_request" | "seller_delist" | "offer_buy" | "offer_buyer_done" | "activity_view") {
    if (!wallet) throw new Error("Connect your wallet first");
    const item = await challenge.mutateAsync({ wallet, action });
    return { challengeId: item.id, signature: await signWalletMessage(item.message) };
  }
  async function loadActivity() {
    try {
      setBusy(true);
      const proof = await walletProof("activity_view");
      await activity.mutateAsync({ wallet, proof });
    } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load wallet activity"); }
    finally { setBusy(false); }
  }
  async function settlePayment() {
    if (!payment) return;
    try {
      setBusy(true);
      if (!payment.recipientWallet || !payment.usdcMint) throw new Error("Payment instructions are unavailable. Please reconnect and try again.");
      const signature = await sendUsdcPayment({ ...payment, amountUsdc: payment.totalUsdc });
      if (payment.kind === "request") await verifyRequestPayment.mutateAsync({ publicId: payment.publicId, wallet, signature });
      else await verifyOfferPayment.mutateAsync({ publicId: payment.publicId, wallet, signature });
      toast.success(payment.kind === "request" ? "Payment verified. Your request is live." : "Payment verified. The seller has been notified.");
      setPayment(null); setModal(null); await refresh();
    } catch (error) { toast.error(error instanceof Error ? error.message : "The payment could not be completed"); }
    finally { setBusy(false); }
  }
  async function startPurchase(publicId: string) {
    try { setBusy(true); const proof = await walletProof("offer_buy"); const created = await startOfferPurchase.mutateAsync({ publicId, wallet, proof }); setPayment({ kind: "offer", ...created }); setModal("buy"); }
    catch (error) { toast.error(error instanceof Error ? error.message : "Could not reserve this seller offer"); }
    finally { setBusy(false); }
  }
  async function markDone(kind: "request-buyer" | "offer-buyer" | "seller", publicId: string) {
    try {
      setBusy(true);
      if (kind === "request-buyer") { const proof = await walletProof("buyer_done"); await buyerDone.mutateAsync({ publicId, wallet, proof }); }
      else if (kind === "offer-buyer") { const proof = await walletProof("offer_buyer_done"); await offerBuyerDone.mutateAsync({ publicId, wallet, proof }); }
      else { const proof = await walletProof("seller_done"); await sellerDone.mutateAsync({ publicId, wallet, proof }); }
      toast.success("Completion marked for review."); await refresh();
    } catch (error) { toast.error(error instanceof Error ? error.message : "Could not mark completion"); }
    finally { setBusy(false); }
  }
  async function delistOffer(publicId: string) { try { setBusy(true); const proof = await walletProof("seller_delist"); await delist.mutateAsync({ publicId, wallet, proof }); toast.success("Seller offer delisted."); await refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not delist offer"); } finally { setBusy(false); } }
  async function cancel(publicId: string) { try { setBusy(true); const proof = await walletProof("cancel_request"); await cancelRequest.mutateAsync({ publicId, wallet, proof }); toast.success("Unpaid request cancelled."); await refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not cancel request"); } finally { setBusy(false); } }

  return <div className="min-h-screen bg-[#ebe9e0] text-[#1b1b19] selection:bg-[#d54f28] selection:text-white">
    <header className="border-b border-[#1b1b19]/25 bg-[#ebe9e0]/90 backdrop-blur"><div className="market-shell flex h-20 items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><Mark /><span className="font-display text-[1.8rem] leading-none tracking-[-0.08em]">Vouch Market</span></Link><nav className="hidden items-center gap-7 text-sm md:flex"><a href="#requests" className="hover:underline">Requests</a><a href="#offers" className="hover:underline">Offers</a><a href="#terms" className="hover:underline">Terms</a></nav>{wallet ? <Button variant="outline" className="border-[#1b1b19]/35 bg-transparent font-mono text-xs" onClick={() => { setModal("activity"); void loadActivity(); }}>{shortWallet(wallet)}</Button> : <Button onClick={connect} disabled={busy} className="bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]"><WalletCards className="mr-2 size-4" />Connect wallet</Button>}</div></header>
    <main><section className="market-shell py-10 sm:py-14"><Link href="/" className="inline-flex items-center gap-2 text-xs uppercase tracking-[.15em] text-[#6b665d] hover:text-[#1b1b19]"><ArrowLeft className="size-3" />Back to Vouch Market</Link><div className="mt-8 flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="eyebrow">Live marketplace</p><h1 className="mt-3 font-display text-[clamp(3.8rem,9vw,7rem)] leading-[.82] tracking-[-.08em]">Find your<br />conviction.</h1></div><div className="max-w-md"><p className="text-sm leading-6 text-[#5b564d]">Choose a project, buy a listed seller offer immediately, or place a request. Prices are participant-set; the reading below is only a live-market signal.</p><div className="mt-5 flex flex-wrap gap-3"><Button className="bg-[#d54f28] text-white hover:bg-[#b93e1c]" onClick={() => setModal("buy")}>Post a request <ArrowUpRight className="ml-2 size-4" /></Button><Button variant="outline" className="border-[#1b1b19]/40 bg-transparent" onClick={() => setModal("sell")}>List points</Button></div></div></div></section>
      <section className="border-y border-[#1b1b19]/25 bg-[#f4f0e6]"><div className="market-shell py-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><p className="eyebrow">Project</p><Select value={project} onValueChange={setProject}><SelectTrigger className="w-52 border-[#1b1b19]/35 bg-transparent"><SelectValue /></SelectTrigger><SelectContent>{projects.map(item => <SelectItem key={item.slug} value={item.slug}>{item.name}</SelectItem>)}</SelectContent></Select></div><p className="max-w-md text-xs leading-5 text-[#625d54]">{selectedProject?.description ?? "Compatible point projects can be added by the marketplace administrator."}</p></div></div></section>
      <section className="market-shell grid gap-8 py-10 xl:grid-cols-[1fr_280px]"><div className="grid gap-8 lg:grid-cols-2"><MarketColumn id="requests" title="Buy requests" count={requests.length}>{board.isLoading ? <Loading /> : requests.length ? requests.map(item => <RequestCard key={item.publicId} item={item} onFill={() => setModal({ fill: item.publicId, remaining: item.requestedQuantity - item.filledQuantity, projectSlug: item.projectSlug })} />) : <Empty label="No funded requests for this project." action="Post the first request" onClick={() => setModal("buy")} />}</MarketColumn><MarketColumn id="offers" title="Seller offers" count={offers.length}>{board.isLoading ? <Loading /> : offers.length ? offers.map(item => <OfferCard key={item.publicId} item={item} buy={() => startPurchase(item.publicId)} disabled={busy || !wallet} />) : <Empty label="No live seller offers for this project." action="List points" onClick={() => setModal("sell")} />}</MarketColumn></div><aside className="relative overflow-hidden border border-[#1b1b19]/30 bg-[#d9d6cc] p-6"><div className="absolute inset-0 opacity-40 mix-blend-multiply paper-grid" /><div className="relative"><p className="eyebrow">Market reading</p><p className="mt-5 font-display text-4xl tracking-[-.06em]">{board.data?.suggestedPricePerVouch ? money(board.data.suggestedPricePerVouch) : "—"}</p><p className="mt-2 text-sm">indicative midpoint per point</p><p className="mt-9 border-t border-[#1b1b19]/25 pt-4 text-sm leading-6 text-[#4d4a43]">Market guidance only. It is never a platform-set price, match promise, or fulfillment guarantee.</p></div></aside></section>
      <section id="terms" className="border-t border-[#1b1b19]/25 bg-[#1b1b19] text-[#f4f0e6]"><div className="market-shell grid gap-8 py-10 md:grid-cols-[.7fr_1.3fr]"><p className="eyebrow text-[#c8c2b3]">Clear terms</p><p className="max-w-3xl text-base leading-7 text-[#e1ddd2]">Buyer payments are verified in Circle-issued USDC on Solana before a purchase or request becomes active. Sellers receive a manually reviewed payout after seller completion and buyer confirmation. A <strong>5% platform fee</strong> is deducted from the seller’s gross amount; the private review desk records the gross amount, fee, and seller net.</p></div></section>
    </main>
    <footer className="market-shell flex flex-wrap items-center justify-between gap-4 py-6 text-xs text-[#666158]"><span>Vouch Market · CommonsMade first</span><span>USDC on Solana · Human-reviewed completions</span></footer>
    <BuyDialog open={modal === "buy"} close={() => { setModal(null); setPayment(null); }} wallet={wallet} connect={connect} projects={projects} project={project} setProject={setProject} sign={walletProof} create={createRequest} payment={payment} setPayment={setPayment} pay={settlePayment} busy={busy} />
    <SellDialog open={modal === "sell"} close={() => setModal(null)} wallet={wallet} connect={connect} projects={projects} project={project} setProject={setProject} sign={walletProof} create={createOffer} busy={busy} />
    <FillDialog target={typeof modal === "object" && modal && "fill" in modal ? modal : null} close={() => setModal(null)} wallet={wallet} connect={connect} sign={walletProof} fill={fill} busy={busy} />
    <ActivityDialog open={modal === "activity"} close={() => setModal(null)} wallet={wallet} data={activity.data} busy={busy} markDone={markDone} cancel={cancel} delist={delistOffer} />
  </div>;
}

function Mark() { return <span className="grid size-8 grid-cols-2 gap-[2px]" aria-hidden>{[0, 1, 2, 3].map(i => <i key={i} className={`block bg-[#1b1b19] ${i === 1 ? "translate-x-1" : ""}`} />)}</span>; }
function MarketColumn({ id, title, count, children }: { id: string; title: string; count: number; children: ReactNode }) { return <div id={id}><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-4xl tracking-[-.06em]">{title}</h2><span className="font-mono text-xs">{String(count).padStart(2, "0")}</span></div><div className="space-y-3">{children}</div></div>; }
function Loading() { return <div className="h-36 animate-pulse border border-[#1b1b19]/15 bg-[#ebe9e0]" />; }
function Empty({ label, action, onClick }: { label: string; action: string; onClick: () => void }) { return <div className="border border-dashed border-[#1b1b19]/30 p-7"><p className="text-sm text-[#5a554c]">{label}</p><button onClick={onClick} className="mt-4 text-sm underline underline-offset-4">{action}</button></div>; }
function Datum({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-[.11em] text-[#777168]">{label}</p><p className="mt-1 truncate text-sm capitalize">{value}</p></div>; }
function RequestCard({ item, onFill }: { item: any; onFill: () => void }) { const left = item.requestedQuantity - item.filledQuantity; return <article className="border border-[#1b1b19]/25 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[#d54f28]">Buying · {stateLabel[item.status]}</p><h3 className="mt-2 font-display text-3xl tracking-[-.05em]">@{item.targetHandle}</h3></div><p className="font-mono text-xs text-[#686158]">{item.publicId}</p></div><div className="mt-6 grid grid-cols-3 border-y border-[#1b1b19]/15 py-3 text-sm"><Datum label="Band" value={item.vouchBand.replaceAll("_", " ")} /><Datum label="Open" value={left.toLocaleString()} /><Datum label="Offer" value={money(item.pricePerVouch)} /></div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-[#686158]">{item.filledQuantity.toLocaleString()} of {item.requestedQuantity.toLocaleString()} filled</p><Button size="sm" variant="outline" className="border-[#1b1b19]/35 bg-transparent" onClick={onFill} disabled={left <= 0}>Fill request</Button></div></article>; }
function OfferCard({ item, buy, disabled }: { item: any; buy: () => void; disabled: boolean }) { return <article className="border border-[#1b1b19]/25 bg-[#e4e1d7] p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Selling · Open</p><h3 className="mt-2 font-display text-3xl tracking-[-.05em]">@{item.profileHandle}</h3></div><p className="font-mono text-xs text-[#686158]">{item.publicId}</p></div><div className="mt-6 grid grid-cols-3 border-y border-[#1b1b19]/15 py-3 text-sm"><Datum label="Band" value={item.vouchBand.replaceAll("_", " ")} /><Datum label="Points" value={item.quantity.toLocaleString()} /><Datum label="Ask" value={money(item.pricePerVouch)} /></div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-[#686158]">Buy this listing directly with USDC.</p><Button size="sm" className="bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]" onClick={buy} disabled={disabled}>{disabled ? "Connect wallet" : "Buy now"}</Button></div></article>; }
function Gate({ connect }: { connect: () => Promise<void> }) { return <div className="mt-5 border border-[#1b1b19]/20 bg-white p-6"><p className="font-display text-2xl tracking-[-.04em]">Connect to continue.</p><p className="mt-2 text-sm leading-6 text-[#625d54]">Your wallet authorizes payments and action-specific confirmations. No public account is created.</p><Button onClick={connect} className="mt-5 bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]"><WalletCards className="mr-2 size-4" />Connect Phantom</Button></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="grid gap-2"><Label className="text-sm font-medium">{label}</Label>{children}</div>; }
function ProjectSelect({ value, setValue, projects }: { value: string; setValue: (value: string) => void; projects: any[] }) { return <Select value={value} onValueChange={setValue}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{projects.map(item => <SelectItem key={item.slug} value={item.slug}>{item.name}</SelectItem>)}</SelectContent></Select>; }
function BandSelect({ value, setValue }: { value: Band; setValue: (value: Band) => void }) { return <Select value={value} onValueChange={setValue as (value: string) => void}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{bands.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select>; }

function BuyDialog({ open, close, wallet, connect, projects, project, setProject, sign, create, payment, setPayment, pay, busy }: any) { const [handle, setHandle] = useState(""); const [band, setBand] = useState<Band>("under_1k"); const [quantity, setQuantity] = useState("100"); const [price, setPrice] = useState("0.50"); const total = Number(quantity || 0) * Number(price || 0); async function submit(event: FormEvent) { event.preventDefault(); try { if (!wallet) throw new Error("Connect your wallet first"); const proof = await sign("buyer_request"); const created = await create.mutateAsync({ wallet, targetHandle: handle, projectSlug: project, vouchBand: band, quantity: Number(quantity), pricePerVouch: Number(price), proof }); setPayment({ kind: "request", ...created }); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not create request"); } }
  const current = payment;
  return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#1b1b19] bg-[#f4f0e6] sm:max-w-lg"><DialogHeader><p className="eyebrow">{current?.kind === "offer" ? "Direct purchase" : "Buyer request"}</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">{current?.kind === "offer" ? "Buy listed points." : "Fund your offer."}</DialogTitle></DialogHeader>{!wallet ? <Gate connect={connect} /> : current ? <div className="mt-4 space-y-5"><div className="border border-[#1b1b19]/25 bg-white p-5"><p className="eyebrow">Exact payment due</p><p className="mt-2 font-display text-4xl tracking-[-.06em]">{money(current.totalUsdc)}</p><p className="mt-3 text-sm leading-6 text-[#5e594f]">Your wallet will open to approve the exact Circle-issued USDC transfer.</p></div><Button className="w-full bg-[#d54f28] text-white hover:bg-[#b93e1c]" onClick={pay} disabled={busy}>{busy ? <><Loader2 className="mr-2 size-4 animate-spin" />Confirming…</> : "Open wallet & pay"}</Button></div> : <form className="mt-4 space-y-5" onSubmit={submit}><Field label="Project"><ProjectSelect value={project} setValue={setProject} projects={projects} /></Field><Field label="Target X handle"><Input value={handle} onChange={e => setHandle(e.target.value)} placeholder="commonsmade" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Point-size band"><BandSelect value={band} setValue={setBand} /></Field><Field label="Points needed"><Input type="number" min="1" value={quantity} onChange={e => setQuantity(e.target.value)} required /></Field></div><Field label="Offer per point (USDC)"><Input type="number" min={band === "under_1k" ? "0.50" : "0.000001"} step="0.000001" value={price} onChange={e => setPrice(e.target.value)} required /></Field><div className="border-y border-[#1b1b19]/20 py-3 text-sm"><div className="flex justify-between"><span>Exact USDC payment</span><strong>{money(total)}</strong></div><p className="mt-2 text-xs leading-5 text-[#625d54]">Under-1k requests require at least 0.50 USDC per point. A 5% marketplace fee is calculated from seller proceeds, not added to this payment.</p></div><Button type="submit" className="w-full bg-[#d54f28] text-white hover:bg-[#b93e1c]" disabled={busy}>Continue to USDC payment</Button></form>}</DialogContent></Dialog>; }
function SellDialog({ open, close, wallet, connect, projects, project, setProject, sign, create, busy }: any) { const [handle, setHandle] = useState(""); const [band, setBand] = useState<Band>("under_1k"); const [quantity, setQuantity] = useState("100"); const [price, setPrice] = useState("0.50"); async function submit(event: FormEvent) { event.preventDefault(); try { if (!wallet) throw new Error("Connect your wallet first"); const proof = await sign("seller_offer"); const result = await create.mutateAsync({ wallet, profileHandle: handle, projectSlug: project, vouchBand: band, quantity: Number(quantity), pricePerVouch: Number(price), proof }); toast.success(`${result.publicId} is now live.`); close(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not post offer"); } } return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="border-[#1b1b19] bg-[#f4f0e6] sm:max-w-lg"><DialogHeader><p className="eyebrow">Seller offer</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">List your points.</DialogTitle></DialogHeader>{!wallet ? <Gate connect={connect} /> : <form className="mt-4 space-y-5" onSubmit={submit}><Field label="Project"><ProjectSelect value={project} setValue={setProject} projects={projects} /></Field><Field label="Your X handle"><Input value={handle} onChange={e => setHandle(e.target.value)} placeholder="yourhandle" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Point-size band"><BandSelect value={band} setValue={setBand} /></Field><Field label="Points available"><Input type="number" min="1" value={quantity} onChange={e => setQuantity(e.target.value)} required /></Field></div><Field label="Ask per point (USDC)"><Input type="number" min="0.000001" step="0.000001" value={price} onChange={e => setPrice(e.target.value)} required /></Field><p className="text-xs leading-5 text-[#625d54]">A 5% platform fee is retained from the seller’s gross amount after a verified purchase and manual review. You can delist while this offer remains open.</p><Button type="submit" className="w-full bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]" disabled={busy}>Sign & post offer</Button></form>}</DialogContent></Dialog>; }
function FillDialog({ target, close, wallet, connect, sign, fill, busy }: any) { const [handle, setHandle] = useState(""); const [quantity, setQuantity] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); try { if (!wallet) throw new Error("Connect your wallet first"); const proof = await sign("seller_fill"); const result = await fill.mutateAsync({ requestPublicId: target.fill, wallet, profileHandle: handle, quantity: Number(quantity), proof }); toast.success(`${result.publicId} is matched to the request.`); close(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not fill request"); } } return <Dialog open={Boolean(target)} onOpenChange={value => !value && close()}><DialogContent className="border-[#1b1b19] bg-[#f4f0e6] sm:max-w-lg"><DialogHeader><p className="eyebrow">Fill request</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">Commit your points.</DialogTitle></DialogHeader>{!wallet ? <Gate connect={connect} /> : <form className="mt-4 space-y-5" onSubmit={submit}><p className="text-sm leading-6 text-[#5e594f]">{target?.remaining.toLocaleString()} points remain on {target?.fill}.</p><Field label="Your X handle"><Input value={handle} onChange={e => setHandle(e.target.value)} placeholder="yourhandle" required /></Field><Field label="Points to fill"><Input type="number" min="1" max={target?.remaining} value={quantity} onChange={e => setQuantity(e.target.value)} required /></Field><Button type="submit" className="w-full bg-[#1b1b19] text-[#f4f0e6] hover:bg-[#34332f]" disabled={busy}>Sign & fill</Button></form>}</DialogContent></Dialog>; }
function ActivityDialog({ open, close, wallet, data, busy, markDone, cancel, delist }: any) { return <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#1b1b19] bg-[#f4f0e6] sm:max-w-xl"><DialogHeader><p className="eyebrow">Wallet activity</p><DialogTitle className="font-display text-4xl tracking-[-.06em]">{wallet && shortWallet(wallet)}</DialogTitle></DialogHeader><div className="mt-4 space-y-7"><ActivityGroup title="Buyer requests">{data?.requests?.length ? data.requests.map((item: any) => <ActivityRow key={item.publicId} text={`${item.publicId} · @${item.targetHandle}`} detail={`${item.filledQuantity}/${item.requestedQuantity} filled · ${money(item.totalUsdc)} · ${stateLabel[item.status] ?? item.status}`} action={item.status === "filled" && !item.buyerMarkedDoneAt ? <Button size="sm" onClick={() => markDone("request-buyer", item.publicId)} disabled={busy}>Confirm task</Button> : item.status === "awaiting_payment" ? <Button size="sm" variant="outline" onClick={() => cancel(item.publicId)} disabled={busy}>Cancel</Button> : null} />) : <Muted text="No buyer requests for this wallet." />}</ActivityGroup><ActivityGroup title="Direct purchases">{data?.purchases?.length ? data.purchases.map((item: any) => <ActivityRow key={item.publicId} text={`${item.publicId} · @${item.profileHandle}`} detail={`${item.quantity} points · ${money(item.grossUsdc)} · ${stateLabel[item.status] ?? item.status}`} action={["matched", "done"].includes(item.status) && !item.buyerMarkedDoneAt ? <Button size="sm" onClick={() => markDone("offer-buyer", item.publicId)} disabled={busy}>Confirm task</Button> : null} />) : <Muted text="No direct purchases for this wallet." />}</ActivityGroup><ActivityGroup title="Seller listings & fills">{data?.fills?.length ? data.fills.map((item: any) => <ActivityRow key={item.publicId} text={`${item.publicId} · @${item.profileHandle}`} detail={`${item.quantity} points · ${money(item.pricePerVouch)} each · ${stateLabel[item.status] ?? item.status}`} action={item.status === "open" ? <Button size="sm" variant="outline" onClick={() => delist(item.publicId)} disabled={busy}><X className="mr-1 size-3" />Delist</Button> : item.status === "matched" ? <Button size="sm" onClick={() => markDone("seller", item.publicId)} disabled={busy}><Check className="mr-1 size-3" />Mark done</Button> : null} />) : <Muted text="No seller activity for this wallet." />}</ActivityGroup><p className="border-t border-[#1b1b19]/20 pt-4 text-xs leading-5 text-[#625d54]">Completion marks are participant statements for human review. They do not automatically release payment.</p></div></DialogContent></Dialog>; }
function ActivityGroup({ title, children }: { title: string; children: ReactNode }) { return <div><p className="eyebrow">{title}</p><div className="mt-3 space-y-2">{children}</div></div>; }
function ActivityRow({ text, detail, action }: { text: string; detail: string; action?: ReactNode }) { return <div className="flex flex-wrap items-center justify-between gap-3 border border-[#1b1b19]/20 bg-white p-4"><div><p className="text-sm font-semibold">{text}</p><p className="mt-1 text-xs text-[#686158]">{detail}</p></div>{action}</div>; }
function Muted({ text }: { text: string }) { return <p className="text-sm text-[#686158]">{text}</p>; }
